[workspace]
resolver = "3"
members = ["crates/*", "services/*"]


[workspace.package]
name = "touchdown"
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
license = "MIT"

[workspace.dependencies]
shared = { path = "crates/shared" }
contracts = { path = "crates/contracts" }

# ======== HTTP =======
axum = { version = "0.8.9", features = ["macros", "ws"] }
tower = { version = "0.5.3", features = ["util", "timeout", "limit"] }
tower-http = { version = "0.7", features = [
    "cors",
    "trace",
    "compression-gzip",
    "request-id",
    "set-header",
    "timeout",
] }
hyper = "1.11.0"

# ======== async / runtime =======
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["rt"] }
futures = "0.3"
async-trait = "0.1"

# ======== Messaging ========
async-nats = "0.50.0"

thiserror = "2.0.20"
anyhow = "1.0.104"

# ========= Serialization =============
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
# ========= Security ============
pasetors = { version = "0.8", features = ["v4", "std"] }
argon2 = { version = "0.5", features = ["std"] }
rand = "0.10.2"
sha2 = "0.11"
hex = "0.4.3"
base64 = "0.23"


# ========= Observability =============
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = [
    "env-filter",
    "json",
    "fmt",
] }
tracing-opentelemetry = "0.33.0"
opentelemetry = "0.32.0"
opentelemetry_sdk = { version = "0.32.1", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.32.0", features = ["grpc-tonic", "trace"] }

# ========== tests ============
testcontainers = "0.27"
testcontainers-modules = { version = "0.15", features = [
    "postgres",
    "redis",
    "minio",
] }

# ========== persistence ==============
sqlx = { version = "0.9.0", default-features = false, features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
    "uuid",
    "chrono",
    "json",
    "migrate",
    "macros",
] }

# ====== doc API =======
utoipa = { version = "5.5", features = ["axum_extras", "chrono", "uuid"] }
utoipa-axum = "0.2"
utoipa-swagger-ui = { version = "9", features = ["axum"] }

# ======== misc ======
uuid = { version = "1.24", features = ["v7", "serde"] }
dotenvy = "0.15.7"
chrono = { version = "0.4", features = ["serde"] }

reqwest = { version = "0.13.4", features = ["json"] }
validator = { version = "0.21", features = ["derive"] }
