[package]
name = "contracts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
shared = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
utoipa = { workspace = true }
validator = { workspace = true }
